### ISSUE TITLE
NullPointerException on orientation change

### ISSUE THREAD

**Issue by vatsalengg** [raymondkam/Ti.SwipeRefreshLayout#4]
Hi, 
I am using this swipe refresh layout as follows. It's working fine before orientation change.

<code>
var menu = Alloy.createController('menu'); 
var swipeRefreshModule = require('com.rkam.swiperefreshlayout'); 
var swipeRefresh = swipeRefreshModule.createSwipeRefresh({
        view: menu.getView(),
        height: Ti.UI.FILL,
        left : 0,
        width: (Alloy.isHandheld)?225:72
    }); 
$.leftWindow.add(swipeRefresh);// $.leftWindow is container of swipeRefresh
</code>

On orientation change following null pointer exception occurs:

dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4155bba8)
[WARN] :   W/System.err: java.lang.NullPointerException
[WARN] :   W/System.err:    at ti.modules.titanium.ui.widget.tableview.TiTableViewRowProxyItem.setRowData(TiTableViewRowProxyItem.java:353)
[WARN] :   W/System.err:    at ti.modules.titanium.ui.widget.tableview.TiTableViewRowProxyItem.setRowData(TiTableViewRowProxyItem.java:91)
[WARN] :   W/System.err:    at ti.modules.titanium.ui.widget.tableview.TiTableView$TTVListAdapter.getView(TiTableView.java:237)
[WARN] :   W/System.err:    at android.widget.AbsListView.obtainView(AbsListView.java:2240)
[WARN] :   W/System.err:    at android.widget.ListView.makeAndAddView(ListView.java:1790)
[WARN] :   W/System.err:    at android.widget.ListView.fillDown(ListView.java:691)
[WARN] :   W/System.err:    at android.widget.ListView.fillSpecific(ListView.java:1349)
[WARN] :   W/System.err:    at android.widget.ListView.layoutChildren(ListView.java:1608)
[WARN] :   W/System.err:    at android.widget.AbsListView.onLayout(AbsListView.java:2091)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[WARN] :   W/System.err:    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[WARN] :   W/System.err:    at ti.modules.titanium.ui.widget.tableview.TiTableView.onLayout(TiTableView.java:620)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[WARN] :   W/System.err:    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at org.appcelerator.titanium.view.TiCompositeLayout.onLayout(TiCompositeLayout.java:575)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[WARN] :   W/System.err:    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
[WARN] :   W/System.err:    at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
[WARN] :   W/System.err:    at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
[WARN] :   W/System.err:    at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
[WARN] :   W/System.err:    at android.view.View.layout(View.java:14817)
[WARN] :   W/System.err:    at android.view.ViewGroup.layout(ViewGroup.java:4631)
[WARN] :   W/System.err:    at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1987)
[WARN] :   W/System.err:    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1744)
[WARN] :   W/System.err:    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
[WARN] :   W/System.err:    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
[WARN] :   W/System.err:    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
[WARN] :   W/System.err:    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
[WARN] :   W/System.err:    at android.view.Choreographer.doFrame(Choreographer.java:544)
[WARN] :   W/System.err:    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
[WARN] :   W/System.err:    at android.os.Handler.handleCallback(Handler.java:733)
[WARN] :   W/System.err:    at android.os.Handler.dispatchMessage(Handler.java:95)
[WARN] :   W/System.err:    at android.os.Looper.loop(Looper.java:136)
[WARN] :   W/System.err:    at android.app.ActivityThread.main(ActivityThread.java:5017)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invokeNative(Native Method)
[WARN] :   W/System.err:    at java.lang.reflect.Method.invoke(Method.java:515)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
[WARN] :   W/System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
[WARN] :   W/System.err:    at dalvik.system.NativeStart.main(Native Method)

@raymondkam, can you suggest any solution?

**Comment by DFoxinator** [comment]
@vatsalengg I've been getting some crash reports with this exact same error. Can you share any more insight on how you fixed this?
